[versions]
agp = "8.8.2"
kotlin = "2.0.0"
coreKtx = "1.15.0"
composeBom = "2024.10.01"
lifecycle = "2.6.2"
activityCompose = "1.9.0"
navigation = "2.7.3"
coil = "2.4.0"
maps = "18.2.0"
location = "21.0.1"
playServicesLocation = "21.3.0"
remoteCreationCore = "1.0.0-alpha02"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "maps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "location" }
gms-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-remote-creation-core = { group = "androidx.compose.remote", name = "remote-creation-core", version.ref = "remoteCreationCore" }
